// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i ancaeus/internal/port.GeoProvider -o geo_provider_mock.go -n GeoProviderMock -p mocks

import (
	"ancaeus/internal/domain"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// GeoProviderMock implements mm_port.GeoProvider
type GeoProviderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLocate          func(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error)
	funcLocateOrigin    string
	inspectFuncLocate   func(ctx context.Context, aps []domain.AccessPoint)
	afterLocateCounter  uint64
	beforeLocateCounter uint64
	LocateMock          mGeoProviderMockLocate

	funcName          func() (s1 string)
	funcNameOrigin    string
	inspectFuncName   func()
	afterNameCounter  uint64
	beforeNameCounter uint64
	NameMock          mGeoProviderMockName
}

// NewGeoProviderMock returns a mock for mm_port.GeoProvider
func NewGeoProviderMock(t minimock.Tester) *GeoProviderMock {
	m := &GeoProviderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LocateMock = mGeoProviderMockLocate{mock: m}
	m.LocateMock.callArgs = []*GeoProviderMockLocateParams{}

	m.NameMock = mGeoProviderMockName{mock: m}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mGeoProviderMockLocate struct {
	optional           bool
	mock               *GeoProviderMock
	defaultExpectation *GeoProviderMockLocateExpectation
	expectations       []*GeoProviderMockLocateExpectation

	callArgs []*GeoProviderMockLocateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GeoProviderMockLocateExpectation specifies expectation struct of the GeoProvider.Locate
type GeoProviderMockLocateExpectation struct {
	mock               *GeoProviderMock
	params             *GeoProviderMockLocateParams
	paramPtrs          *GeoProviderMockLocateParamPtrs
	expectationOrigins GeoProviderMockLocateExpectationOrigins
	results            *GeoProviderMockLocateResults
	returnOrigin       string
	Counter            uint64
}

// GeoProviderMockLocateParams contains parameters of the GeoProvider.Locate
type GeoProviderMockLocateParams struct {
	ctx context.Context
	aps []domain.AccessPoint
}

// GeoProviderMockLocateParamPtrs contains pointers to parameters of the GeoProvider.Locate
type GeoProviderMockLocateParamPtrs struct {
	ctx *context.Context
	aps *[]domain.AccessPoint
}

// GeoProviderMockLocateResults contains results of the GeoProvider.Locate
type GeoProviderMockLocateResults struct {
	lp1 *domain.Location
	err error
}

// GeoProviderMockLocateOrigins contains origins of expectations of the GeoProvider.Locate
type GeoProviderMockLocateExpectationOrigins struct {
	origin    string
	originCtx string
	originAps string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLocate *mGeoProviderMockLocate) Optional() *mGeoProviderMockLocate {
	mmLocate.optional = true
	return mmLocate
}

// Expect sets up expected params for GeoProvider.Locate
func (mmLocate *mGeoProviderMockLocate) Expect(ctx context.Context, aps []domain.AccessPoint) *mGeoProviderMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &GeoProviderMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.paramPtrs != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by ExpectParams functions")
	}

	mmLocate.defaultExpectation.params = &GeoProviderMockLocateParams{ctx, aps}
	mmLocate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLocate.expectations {
		if minimock.Equal(e.params, mmLocate.defaultExpectation.params) {
			mmLocate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLocate.defaultExpectation.params)
		}
	}

	return mmLocate
}

// ExpectCtxParam1 sets up expected param ctx for GeoProvider.Locate
func (mmLocate *mGeoProviderMockLocate) ExpectCtxParam1(ctx context.Context) *mGeoProviderMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &GeoProviderMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.params != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Expect")
	}

	if mmLocate.defaultExpectation.paramPtrs == nil {
		mmLocate.defaultExpectation.paramPtrs = &GeoProviderMockLocateParamPtrs{}
	}
	mmLocate.defaultExpectation.paramPtrs.ctx = &ctx
	mmLocate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLocate
}

// ExpectApsParam2 sets up expected param aps for GeoProvider.Locate
func (mmLocate *mGeoProviderMockLocate) ExpectApsParam2(aps []domain.AccessPoint) *mGeoProviderMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &GeoProviderMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.params != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Expect")
	}

	if mmLocate.defaultExpectation.paramPtrs == nil {
		mmLocate.defaultExpectation.paramPtrs = &GeoProviderMockLocateParamPtrs{}
	}
	mmLocate.defaultExpectation.paramPtrs.aps = &aps
	mmLocate.defaultExpectation.expectationOrigins.originAps = minimock.CallerInfo(1)

	return mmLocate
}

// Inspect accepts an inspector function that has same arguments as the GeoProvider.Locate
func (mmLocate *mGeoProviderMockLocate) Inspect(f func(ctx context.Context, aps []domain.AccessPoint)) *mGeoProviderMockLocate {
	if mmLocate.mock.inspectFuncLocate != nil {
		mmLocate.mock.t.Fatalf("Inspect function is already set for GeoProviderMock.Locate")
	}

	mmLocate.mock.inspectFuncLocate = f

	return mmLocate
}

// Return sets up results that will be returned by GeoProvider.Locate
func (mmLocate *mGeoProviderMockLocate) Return(lp1 *domain.Location, err error) *GeoProviderMock {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &GeoProviderMockLocateExpectation{mock: mmLocate.mock}
	}
	mmLocate.defaultExpectation.results = &GeoProviderMockLocateResults{lp1, err}
	mmLocate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLocate.mock
}

// Set uses given function f to mock the GeoProvider.Locate method
func (mmLocate *mGeoProviderMockLocate) Set(f func(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error)) *GeoProviderMock {
	if mmLocate.defaultExpectation != nil {
		mmLocate.mock.t.Fatalf("Default expectation is already set for the GeoProvider.Locate method")
	}

	if len(mmLocate.expectations) > 0 {
		mmLocate.mock.t.Fatalf("Some expectations are already set for the GeoProvider.Locate method")
	}

	mmLocate.mock.funcLocate = f
	mmLocate.mock.funcLocateOrigin = minimock.CallerInfo(1)
	return mmLocate.mock
}

// When sets expectation for the GeoProvider.Locate which will trigger the result defined by the following
// Then helper
func (mmLocate *mGeoProviderMockLocate) When(ctx context.Context, aps []domain.AccessPoint) *GeoProviderMockLocateExpectation {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("GeoProviderMock.Locate mock is already set by Set")
	}

	expectation := &GeoProviderMockLocateExpectation{
		mock:               mmLocate.mock,
		params:             &GeoProviderMockLocateParams{ctx, aps},
		expectationOrigins: GeoProviderMockLocateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLocate.expectations = append(mmLocate.expectations, expectation)
	return expectation
}

// Then sets up GeoProvider.Locate return parameters for the expectation previously defined by the When method
func (e *GeoProviderMockLocateExpectation) Then(lp1 *domain.Location, err error) *GeoProviderMock {
	e.results = &GeoProviderMockLocateResults{lp1, err}
	return e.mock
}

// Times sets number of times GeoProvider.Locate should be invoked
func (mmLocate *mGeoProviderMockLocate) Times(n uint64) *mGeoProviderMockLocate {
	if n == 0 {
		mmLocate.mock.t.Fatalf("Times of GeoProviderMock.Locate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLocate.expectedInvocations, n)
	mmLocate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLocate
}

func (mmLocate *mGeoProviderMockLocate) invocationsDone() bool {
	if len(mmLocate.expectations) == 0 && mmLocate.defaultExpectation == nil && mmLocate.mock.funcLocate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLocate.mock.afterLocateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLocate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Locate implements mm_port.GeoProvider
func (mmLocate *GeoProviderMock) Locate(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error) {
	mm_atomic.AddUint64(&mmLocate.beforeLocateCounter, 1)
	defer mm_atomic.AddUint64(&mmLocate.afterLocateCounter, 1)

	mmLocate.t.Helper()

	if mmLocate.inspectFuncLocate != nil {
		mmLocate.inspectFuncLocate(ctx, aps)
	}

	mm_params := GeoProviderMockLocateParams{ctx, aps}

	// Record call args
	mmLocate.LocateMock.mutex.Lock()
	mmLocate.LocateMock.callArgs = append(mmLocate.LocateMock.callArgs, &mm_params)
	mmLocate.LocateMock.mutex.Unlock()

	for _, e := range mmLocate.LocateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.lp1, e.results.err
		}
	}

	if mmLocate.LocateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLocate.LocateMock.defaultExpectation.Counter, 1)
		mm_want := mmLocate.LocateMock.defaultExpectation.params
		mm_want_ptrs := mmLocate.LocateMock.defaultExpectation.paramPtrs

		mm_got := GeoProviderMockLocateParams{ctx, aps}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLocate.t.Errorf("GeoProviderMock.Locate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLocate.LocateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.aps != nil && !minimock.Equal(*mm_want_ptrs.aps, mm_got.aps) {
				mmLocate.t.Errorf("GeoProviderMock.Locate got unexpected parameter aps, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLocate.LocateMock.defaultExpectation.expectationOrigins.originAps, *mm_want_ptrs.aps, mm_got.aps, minimock.Diff(*mm_want_ptrs.aps, mm_got.aps))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLocate.t.Errorf("GeoProviderMock.Locate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLocate.LocateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLocate.LocateMock.defaultExpectation.results
		if mm_results == nil {
			mmLocate.t.Fatal("No results are set for the GeoProviderMock.Locate")
		}
		return (*mm_results).lp1, (*mm_results).err
	}
	if mmLocate.funcLocate != nil {
		return mmLocate.funcLocate(ctx, aps)
	}
	mmLocate.t.Fatalf("Unexpected call to GeoProviderMock.Locate. %v %v", ctx, aps)
	return
}

// LocateAfterCounter returns a count of finished GeoProviderMock.Locate invocations
func (mmLocate *GeoProviderMock) LocateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLocate.afterLocateCounter)
}

// LocateBeforeCounter returns a count of GeoProviderMock.Locate invocations
func (mmLocate *GeoProviderMock) LocateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLocate.beforeLocateCounter)
}

// Calls returns a list of arguments used in each call to GeoProviderMock.Locate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLocate *mGeoProviderMockLocate) Calls() []*GeoProviderMockLocateParams {
	mmLocate.mutex.RLock()

	argCopy := make([]*GeoProviderMockLocateParams, len(mmLocate.callArgs))
	copy(argCopy, mmLocate.callArgs)

	mmLocate.mutex.RUnlock()

	return argCopy
}

// MinimockLocateDone returns true if the count of the Locate invocations corresponds
// the number of defined expectations
func (m *GeoProviderMock) MinimockLocateDone() bool {
	if m.LocateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LocateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LocateMock.invocationsDone()
}

// MinimockLocateInspect logs each unmet expectation
func (m *GeoProviderMock) MinimockLocateInspect() {
	for _, e := range m.LocateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to GeoProviderMock.Locate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLocateCounter := mm_atomic.LoadUint64(&m.afterLocateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LocateMock.defaultExpectation != nil && afterLocateCounter < 1 {
		if m.LocateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to GeoProviderMock.Locate at\n%s", m.LocateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to GeoProviderMock.Locate at\n%s with params: %#v", m.LocateMock.defaultExpectation.expectationOrigins.origin, *m.LocateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLocate != nil && afterLocateCounter < 1 {
		m.t.Errorf("Expected call to GeoProviderMock.Locate at\n%s", m.funcLocateOrigin)
	}

	if !m.LocateMock.invocationsDone() && afterLocateCounter > 0 {
		m.t.Errorf("Expected %d calls to GeoProviderMock.Locate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LocateMock.expectedInvocations), m.LocateMock.expectedInvocationsOrigin, afterLocateCounter)
	}
}

type mGeoProviderMockName struct {
	optional           bool
	mock               *GeoProviderMock
	defaultExpectation *GeoProviderMockNameExpectation
	expectations       []*GeoProviderMockNameExpectation

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// GeoProviderMockNameExpectation specifies expectation struct of the GeoProvider.Name
type GeoProviderMockNameExpectation struct {
	mock *GeoProviderMock

	results      *GeoProviderMockNameResults
	returnOrigin string
	Counter      uint64
}

// GeoProviderMockNameResults contains results of the GeoProvider.Name
type GeoProviderMockNameResults struct {
	s1 string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmName *mGeoProviderMockName) Optional() *mGeoProviderMockName {
	mmName.optional = true
	return mmName
}

// Expect sets up expected params for GeoProvider.Name
func (mmName *mGeoProviderMockName) Expect() *mGeoProviderMockName {
	if mmName.mock.funcName != nil {
		mmName.mock.t.Fatalf("GeoProviderMock.Name mock is already set by Set")
	}

	if mmName.defaultExpectation == nil {
		mmName.defaultExpectation = &GeoProviderMockNameExpectation{}
	}

	return mmName
}

// Inspect accepts an inspector function that has same arguments as the GeoProvider.Name
func (mmName *mGeoProviderMockName) Inspect(f func()) *mGeoProviderMockName {
	if mmName.mock.inspectFuncName != nil {
		mmName.mock.t.Fatalf("Inspect function is already set for GeoProviderMock.Name")
	}

	mmName.mock.inspectFuncName = f

	return mmName
}

// Return sets up results that will be returned by GeoProvider.Name
func (mmName *mGeoProviderMockName) Return(s1 string) *GeoProviderMock {
	if mmName.mock.funcName != nil {
		mmName.mock.t.Fatalf("GeoProviderMock.Name mock is already set by Set")
	}

	if mmName.defaultExpectation == nil {
		mmName.defaultExpectation = &GeoProviderMockNameExpectation{mock: mmName.mock}
	}
	mmName.defaultExpectation.results = &GeoProviderMockNameResults{s1}
	mmName.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmName.mock
}

// Set uses given function f to mock the GeoProvider.Name method
func (mmName *mGeoProviderMockName) Set(f func() (s1 string)) *GeoProviderMock {
	if mmName.defaultExpectation != nil {
		mmName.mock.t.Fatalf("Default expectation is already set for the GeoProvider.Name method")
	}

	if len(mmName.expectations) > 0 {
		mmName.mock.t.Fatalf("Some expectations are already set for the GeoProvider.Name method")
	}

	mmName.mock.funcName = f
	mmName.mock.funcNameOrigin = minimock.CallerInfo(1)
	return mmName.mock
}

// Times sets number of times GeoProvider.Name should be invoked
func (mmName *mGeoProviderMockName) Times(n uint64) *mGeoProviderMockName {
	if n == 0 {
		mmName.mock.t.Fatalf("Times of GeoProviderMock.Name mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmName.expectedInvocations, n)
	mmName.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmName
}

func (mmName *mGeoProviderMockName) invocationsDone() bool {
	if len(mmName.expectations) == 0 && mmName.defaultExpectation == nil && mmName.mock.funcName == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmName.mock.afterNameCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmName.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Name implements mm_port.GeoProvider
func (mmName *GeoProviderMock) Name() (s1 string) {
	mm_atomic.AddUint64(&mmName.beforeNameCounter, 1)
	defer mm_atomic.AddUint64(&mmName.afterNameCounter, 1)

	mmName.t.Helper()

	if mmName.inspectFuncName != nil {
		mmName.inspectFuncName()
	}

	if mmName.NameMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmName.NameMock.defaultExpectation.Counter, 1)

		mm_results := mmName.NameMock.defaultExpectation.results
		if mm_results == nil {
			mmName.t.Fatal("No results are set for the GeoProviderMock.Name")
		}
		return (*mm_results).s1
	}
	if mmName.funcName != nil {
		return mmName.funcName()
	}
	mmName.t.Fatalf("Unexpected call to GeoProviderMock.Name.")
	return
}

// NameAfterCounter returns a count of finished GeoProviderMock.Name invocations
func (mmName *GeoProviderMock) NameAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmName.afterNameCounter)
}

// NameBeforeCounter returns a count of GeoProviderMock.Name invocations
func (mmName *GeoProviderMock) NameBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmName.beforeNameCounter)
}

// MinimockNameDone returns true if the count of the Name invocations corresponds
// the number of defined expectations
func (m *GeoProviderMock) MinimockNameDone() bool {
	if m.NameMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.NameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.NameMock.invocationsDone()
}

// MinimockNameInspect logs each unmet expectation
func (m *GeoProviderMock) MinimockNameInspect() {
	for _, e := range m.NameMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to GeoProviderMock.Name")
		}
	}

	afterNameCounter := mm_atomic.LoadUint64(&m.afterNameCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.NameMock.defaultExpectation != nil && afterNameCounter < 1 {
		m.t.Errorf("Expected call to GeoProviderMock.Name at\n%s", m.NameMock.defaultExpectation.returnOrigin)
	}
	// if func was set then invocations count should be greater than zero
	if m.funcName != nil && afterNameCounter < 1 {
		m.t.Errorf("Expected call to GeoProviderMock.Name at\n%s", m.funcNameOrigin)
	}

	if !m.NameMock.invocationsDone() && afterNameCounter > 0 {
		m.t.Errorf("Expected %d calls to GeoProviderMock.Name at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.NameMock.expectedInvocations), m.NameMock.expectedInvocationsOrigin, afterNameCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *GeoProviderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLocateInspect()

			m.MinimockNameInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *GeoProviderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *GeoProviderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLocateDone() &&
		m.MinimockNameDone()
}
