// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i ancaeus/internal/port.Radio -o radio_mock.go -n RadioMock -p mocks

import (
	"ancaeus/internal/domain"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RadioMock implements mm_port.Radio
type RadioMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcScan          func(ctx context.Context, full bool) (aa1 []domain.AccessPoint, err error)
	funcScanOrigin    string
	inspectFuncScan   func(ctx context.Context, full bool)
	afterScanCounter  uint64
	beforeScanCounter uint64
	ScanMock          mRadioMockScan
}

// NewRadioMock returns a mock for mm_port.Radio
func NewRadioMock(t minimock.Tester) *RadioMock {
	m := &RadioMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ScanMock = mRadioMockScan{mock: m}
	m.ScanMock.callArgs = []*RadioMockScanParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRadioMockScan struct {
	optional           bool
	mock               *RadioMock
	defaultExpectation *RadioMockScanExpectation
	expectations       []*RadioMockScanExpectation

	callArgs []*RadioMockScanParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RadioMockScanExpectation specifies expectation struct of the Radio.Scan
type RadioMockScanExpectation struct {
	mock               *RadioMock
	params             *RadioMockScanParams
	paramPtrs          *RadioMockScanParamPtrs
	expectationOrigins RadioMockScanExpectationOrigins
	results            *RadioMockScanResults
	returnOrigin       string
	Counter            uint64
}

// RadioMockScanParams contains parameters of the Radio.Scan
type RadioMockScanParams struct {
	ctx  context.Context
	full bool
}

// RadioMockScanParamPtrs contains pointers to parameters of the Radio.Scan
type RadioMockScanParamPtrs struct {
	ctx  *context.Context
	full *bool
}

// RadioMockScanResults contains results of the Radio.Scan
type RadioMockScanResults struct {
	aa1 []domain.AccessPoint
	err error
}

// RadioMockScanOrigins contains origins of expectations of the Radio.Scan
type RadioMockScanExpectationOrigins struct {
	origin     string
	originCtx  string
	originFull string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmScan *mRadioMockScan) Optional() *mRadioMockScan {
	mmScan.optional = true
	return mmScan
}

// Expect sets up expected params for Radio.Scan
func (mmScan *mRadioMockScan) Expect(ctx context.Context, full bool) *mRadioMockScan {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &RadioMockScanExpectation{}
	}

	if mmScan.defaultExpectation.paramPtrs != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by ExpectParams functions")
	}

	mmScan.defaultExpectation.params = &RadioMockScanParams{ctx, full}
	mmScan.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmScan.expectations {
		if minimock.Equal(e.params, mmScan.defaultExpectation.params) {
			mmScan.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmScan.defaultExpectation.params)
		}
	}

	return mmScan
}

// ExpectCtxParam1 sets up expected param ctx for Radio.Scan
func (mmScan *mRadioMockScan) ExpectCtxParam1(ctx context.Context) *mRadioMockScan {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &RadioMockScanExpectation{}
	}

	if mmScan.defaultExpectation.params != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Expect")
	}

	if mmScan.defaultExpectation.paramPtrs == nil {
		mmScan.defaultExpectation.paramPtrs = &RadioMockScanParamPtrs{}
	}
	mmScan.defaultExpectation.paramPtrs.ctx = &ctx
	mmScan.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmScan
}

// ExpectFullParam2 sets up expected param full for Radio.Scan
func (mmScan *mRadioMockScan) ExpectFullParam2(full bool) *mRadioMockScan {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &RadioMockScanExpectation{}
	}

	if mmScan.defaultExpectation.params != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Expect")
	}

	if mmScan.defaultExpectation.paramPtrs == nil {
		mmScan.defaultExpectation.paramPtrs = &RadioMockScanParamPtrs{}
	}
	mmScan.defaultExpectation.paramPtrs.full = &full
	mmScan.defaultExpectation.expectationOrigins.originFull = minimock.CallerInfo(1)

	return mmScan
}

// Inspect accepts an inspector function that has same arguments as the Radio.Scan
func (mmScan *mRadioMockScan) Inspect(f func(ctx context.Context, full bool)) *mRadioMockScan {
	if mmScan.mock.inspectFuncScan != nil {
		mmScan.mock.t.Fatalf("Inspect function is already set for RadioMock.Scan")
	}

	mmScan.mock.inspectFuncScan = f

	return mmScan
}

// Return sets up results that will be returned by Radio.Scan
func (mmScan *mRadioMockScan) Return(aa1 []domain.AccessPoint, err error) *RadioMock {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Set")
	}

	if mmScan.defaultExpectation == nil {
		mmScan.defaultExpectation = &RadioMockScanExpectation{mock: mmScan.mock}
	}
	mmScan.defaultExpectation.results = &RadioMockScanResults{aa1, err}
	mmScan.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmScan.mock
}

// Set uses given function f to mock the Radio.Scan method
func (mmScan *mRadioMockScan) Set(f func(ctx context.Context, full bool) (aa1 []domain.AccessPoint, err error)) *RadioMock {
	if mmScan.defaultExpectation != nil {
		mmScan.mock.t.Fatalf("Default expectation is already set for the Radio.Scan method")
	}

	if len(mmScan.expectations) > 0 {
		mmScan.mock.t.Fatalf("Some expectations are already set for the Radio.Scan method")
	}

	mmScan.mock.funcScan = f
	mmScan.mock.funcScanOrigin = minimock.CallerInfo(1)
	return mmScan.mock
}

// When sets expectation for the Radio.Scan which will trigger the result defined by the following
// Then helper
func (mmScan *mRadioMockScan) When(ctx context.Context, full bool) *RadioMockScanExpectation {
	if mmScan.mock.funcScan != nil {
		mmScan.mock.t.Fatalf("RadioMock.Scan mock is already set by Set")
	}

	expectation := &RadioMockScanExpectation{
		mock:               mmScan.mock,
		params:             &RadioMockScanParams{ctx, full},
		expectationOrigins: RadioMockScanExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmScan.expectations = append(mmScan.expectations, expectation)
	return expectation
}

// Then sets up Radio.Scan return parameters for the expectation previously defined by the When method
func (e *RadioMockScanExpectation) Then(aa1 []domain.AccessPoint, err error) *RadioMock {
	e.results = &RadioMockScanResults{aa1, err}
	return e.mock
}

// Times sets number of times Radio.Scan should be invoked
func (mmScan *mRadioMockScan) Times(n uint64) *mRadioMockScan {
	if n == 0 {
		mmScan.mock.t.Fatalf("Times of RadioMock.Scan mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmScan.expectedInvocations, n)
	mmScan.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmScan
}

func (mmScan *mRadioMockScan) invocationsDone() bool {
	if len(mmScan.expectations) == 0 && mmScan.defaultExpectation == nil && mmScan.mock.funcScan == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmScan.mock.afterScanCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmScan.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Scan implements mm_port.Radio
func (mmScan *RadioMock) Scan(ctx context.Context, full bool) (aa1 []domain.AccessPoint, err error) {
	mm_atomic.AddUint64(&mmScan.beforeScanCounter, 1)
	defer mm_atomic.AddUint64(&mmScan.afterScanCounter, 1)

	mmScan.t.Helper()

	if mmScan.inspectFuncScan != nil {
		mmScan.inspectFuncScan(ctx, full)
	}

	mm_params := RadioMockScanParams{ctx, full}

	// Record call args
	mmScan.ScanMock.mutex.Lock()
	mmScan.ScanMock.callArgs = append(mmScan.ScanMock.callArgs, &mm_params)
	mmScan.ScanMock.mutex.Unlock()

	for _, e := range mmScan.ScanMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.aa1, e.results.err
		}
	}

	if mmScan.ScanMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmScan.ScanMock.defaultExpectation.Counter, 1)
		mm_want := mmScan.ScanMock.defaultExpectation.params
		mm_want_ptrs := mmScan.ScanMock.defaultExpectation.paramPtrs

		mm_got := RadioMockScanParams{ctx, full}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmScan.t.Errorf("RadioMock.Scan got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmScan.ScanMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.full != nil && !minimock.Equal(*mm_want_ptrs.full, mm_got.full) {
				mmScan.t.Errorf("RadioMock.Scan got unexpected parameter full, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmScan.ScanMock.defaultExpectation.expectationOrigins.originFull, *mm_want_ptrs.full, mm_got.full, minimock.Diff(*mm_want_ptrs.full, mm_got.full))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmScan.t.Errorf("RadioMock.Scan got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmScan.ScanMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmScan.ScanMock.defaultExpectation.results
		if mm_results == nil {
			mmScan.t.Fatal("No results are set for the RadioMock.Scan")
		}
		return (*mm_results).aa1, (*mm_results).err
	}
	if mmScan.funcScan != nil {
		return mmScan.funcScan(ctx, full)
	}
	mmScan.t.Fatalf("Unexpected call to RadioMock.Scan. %v %v", ctx, full)
	return
}

// ScanAfterCounter returns a count of finished RadioMock.Scan invocations
func (mmScan *RadioMock) ScanAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScan.afterScanCounter)
}

// ScanBeforeCounter returns a count of RadioMock.Scan invocations
func (mmScan *RadioMock) ScanBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmScan.beforeScanCounter)
}

// Calls returns a list of arguments used in each call to RadioMock.Scan.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmScan *mRadioMockScan) Calls() []*RadioMockScanParams {
	mmScan.mutex.RLock()

	argCopy := make([]*RadioMockScanParams, len(mmScan.callArgs))
	copy(argCopy, mmScan.callArgs)

	mmScan.mutex.RUnlock()

	return argCopy
}

// MinimockScanDone returns true if the count of the Scan invocations corresponds
// the number of defined expectations
func (m *RadioMock) MinimockScanDone() bool {
	if m.ScanMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ScanMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ScanMock.invocationsDone()
}

// MinimockScanInspect logs each unmet expectation
func (m *RadioMock) MinimockScanInspect() {
	for _, e := range m.ScanMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RadioMock.Scan at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterScanCounter := mm_atomic.LoadUint64(&m.afterScanCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ScanMock.defaultExpectation != nil && afterScanCounter < 1 {
		if m.ScanMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RadioMock.Scan at\n%s", m.ScanMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RadioMock.Scan at\n%s with params: %#v", m.ScanMock.defaultExpectation.expectationOrigins.origin, *m.ScanMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcScan != nil && afterScanCounter < 1 {
		m.t.Errorf("Expected call to RadioMock.Scan at\n%s", m.funcScanOrigin)
	}

	if !m.ScanMock.invocationsDone() && afterScanCounter > 0 {
		m.t.Errorf("Expected %d calls to RadioMock.Scan at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ScanMock.expectedInvocations), m.ScanMock.expectedInvocationsOrigin, afterScanCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RadioMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockScanInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RadioMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RadioMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockScanDone()
}
