// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i ancaeus/internal/port.WifiLocator -o wifi_locator_mock.go -n WifiLocatorMock -p mocks

import (
	"ancaeus/internal/domain"
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// WifiLocatorMock implements mm_port.WifiLocator
type WifiLocatorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcLocate          func(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error)
	funcLocateOrigin    string
	inspectFuncLocate   func(ctx context.Context, aps []domain.AccessPoint)
	afterLocateCounter  uint64
	beforeLocateCounter uint64
	LocateMock          mWifiLocatorMockLocate
}

// NewWifiLocatorMock returns a mock for mm_port.WifiLocator
func NewWifiLocatorMock(t minimock.Tester) *WifiLocatorMock {
	m := &WifiLocatorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.LocateMock = mWifiLocatorMockLocate{mock: m}
	m.LocateMock.callArgs = []*WifiLocatorMockLocateParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mWifiLocatorMockLocate struct {
	optional           bool
	mock               *WifiLocatorMock
	defaultExpectation *WifiLocatorMockLocateExpectation
	expectations       []*WifiLocatorMockLocateExpectation

	callArgs []*WifiLocatorMockLocateParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// WifiLocatorMockLocateExpectation specifies expectation struct of the WifiLocator.Locate
type WifiLocatorMockLocateExpectation struct {
	mock               *WifiLocatorMock
	params             *WifiLocatorMockLocateParams
	paramPtrs          *WifiLocatorMockLocateParamPtrs
	expectationOrigins WifiLocatorMockLocateExpectationOrigins
	results            *WifiLocatorMockLocateResults
	returnOrigin       string
	Counter            uint64
}

// WifiLocatorMockLocateParams contains parameters of the WifiLocator.Locate
type WifiLocatorMockLocateParams struct {
	ctx context.Context
	aps []domain.AccessPoint
}

// WifiLocatorMockLocateParamPtrs contains pointers to parameters of the WifiLocator.Locate
type WifiLocatorMockLocateParamPtrs struct {
	ctx *context.Context
	aps *[]domain.AccessPoint
}

// WifiLocatorMockLocateResults contains results of the WifiLocator.Locate
type WifiLocatorMockLocateResults struct {
	lp1 *domain.Location
	err error
}

// WifiLocatorMockLocateOrigins contains origins of expectations of the WifiLocator.Locate
type WifiLocatorMockLocateExpectationOrigins struct {
	origin    string
	originCtx string
	originAps string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmLocate *mWifiLocatorMockLocate) Optional() *mWifiLocatorMockLocate {
	mmLocate.optional = true
	return mmLocate
}

// Expect sets up expected params for WifiLocator.Locate
func (mmLocate *mWifiLocatorMockLocate) Expect(ctx context.Context, aps []domain.AccessPoint) *mWifiLocatorMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &WifiLocatorMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.paramPtrs != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by ExpectParams functions")
	}

	mmLocate.defaultExpectation.params = &WifiLocatorMockLocateParams{ctx, aps}
	mmLocate.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmLocate.expectations {
		if minimock.Equal(e.params, mmLocate.defaultExpectation.params) {
			mmLocate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmLocate.defaultExpectation.params)
		}
	}

	return mmLocate
}

// ExpectCtxParam1 sets up expected param ctx for WifiLocator.Locate
func (mmLocate *mWifiLocatorMockLocate) ExpectCtxParam1(ctx context.Context) *mWifiLocatorMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &WifiLocatorMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.params != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Expect")
	}

	if mmLocate.defaultExpectation.paramPtrs == nil {
		mmLocate.defaultExpectation.paramPtrs = &WifiLocatorMockLocateParamPtrs{}
	}
	mmLocate.defaultExpectation.paramPtrs.ctx = &ctx
	mmLocate.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmLocate
}

// ExpectApsParam2 sets up expected param aps for WifiLocator.Locate
func (mmLocate *mWifiLocatorMockLocate) ExpectApsParam2(aps []domain.AccessPoint) *mWifiLocatorMockLocate {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &WifiLocatorMockLocateExpectation{}
	}

	if mmLocate.defaultExpectation.params != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Expect")
	}

	if mmLocate.defaultExpectation.paramPtrs == nil {
		mmLocate.defaultExpectation.paramPtrs = &WifiLocatorMockLocateParamPtrs{}
	}
	mmLocate.defaultExpectation.paramPtrs.aps = &aps
	mmLocate.defaultExpectation.expectationOrigins.originAps = minimock.CallerInfo(1)

	return mmLocate
}

// Inspect accepts an inspector function that has same arguments as the WifiLocator.Locate
func (mmLocate *mWifiLocatorMockLocate) Inspect(f func(ctx context.Context, aps []domain.AccessPoint)) *mWifiLocatorMockLocate {
	if mmLocate.mock.inspectFuncLocate != nil {
		mmLocate.mock.t.Fatalf("Inspect function is already set for WifiLocatorMock.Locate")
	}

	mmLocate.mock.inspectFuncLocate = f

	return mmLocate
}

// Return sets up results that will be returned by WifiLocator.Locate
func (mmLocate *mWifiLocatorMockLocate) Return(lp1 *domain.Location, err error) *WifiLocatorMock {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Set")
	}

	if mmLocate.defaultExpectation == nil {
		mmLocate.defaultExpectation = &WifiLocatorMockLocateExpectation{mock: mmLocate.mock}
	}
	mmLocate.defaultExpectation.results = &WifiLocatorMockLocateResults{lp1, err}
	mmLocate.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmLocate.mock
}

// Set uses given function f to mock the WifiLocator.Locate method
func (mmLocate *mWifiLocatorMockLocate) Set(f func(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error)) *WifiLocatorMock {
	if mmLocate.defaultExpectation != nil {
		mmLocate.mock.t.Fatalf("Default expectation is already set for the WifiLocator.Locate method")
	}

	if len(mmLocate.expectations) > 0 {
		mmLocate.mock.t.Fatalf("Some expectations are already set for the WifiLocator.Locate method")
	}

	mmLocate.mock.funcLocate = f
	mmLocate.mock.funcLocateOrigin = minimock.CallerInfo(1)
	return mmLocate.mock
}

// When sets expectation for the WifiLocator.Locate which will trigger the result defined by the following
// Then helper
func (mmLocate *mWifiLocatorMockLocate) When(ctx context.Context, aps []domain.AccessPoint) *WifiLocatorMockLocateExpectation {
	if mmLocate.mock.funcLocate != nil {
		mmLocate.mock.t.Fatalf("WifiLocatorMock.Locate mock is already set by Set")
	}

	expectation := &WifiLocatorMockLocateExpectation{
		mock:               mmLocate.mock,
		params:             &WifiLocatorMockLocateParams{ctx, aps},
		expectationOrigins: WifiLocatorMockLocateExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmLocate.expectations = append(mmLocate.expectations, expectation)
	return expectation
}

// Then sets up WifiLocator.Locate return parameters for the expectation previously defined by the When method
func (e *WifiLocatorMockLocateExpectation) Then(lp1 *domain.Location, err error) *WifiLocatorMock {
	e.results = &WifiLocatorMockLocateResults{lp1, err}
	return e.mock
}

// Times sets number of times WifiLocator.Locate should be invoked
func (mmLocate *mWifiLocatorMockLocate) Times(n uint64) *mWifiLocatorMockLocate {
	if n == 0 {
		mmLocate.mock.t.Fatalf("Times of WifiLocatorMock.Locate mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmLocate.expectedInvocations, n)
	mmLocate.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmLocate
}

func (mmLocate *mWifiLocatorMockLocate) invocationsDone() bool {
	if len(mmLocate.expectations) == 0 && mmLocate.defaultExpectation == nil && mmLocate.mock.funcLocate == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmLocate.mock.afterLocateCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmLocate.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Locate implements mm_port.WifiLocator
func (mmLocate *WifiLocatorMock) Locate(ctx context.Context, aps []domain.AccessPoint) (lp1 *domain.Location, err error) {
	mm_atomic.AddUint64(&mmLocate.beforeLocateCounter, 1)
	defer mm_atomic.AddUint64(&mmLocate.afterLocateCounter, 1)

	mmLocate.t.Helper()

	if mmLocate.inspectFuncLocate != nil {
		mmLocate.inspectFuncLocate(ctx, aps)
	}

	mm_params := WifiLocatorMockLocateParams{ctx, aps}

	// Record call args
	mmLocate.LocateMock.mutex.Lock()
	mmLocate.LocateMock.callArgs = append(mmLocate.LocateMock.callArgs, &mm_params)
	mmLocate.LocateMock.mutex.Unlock()

	for _, e := range mmLocate.LocateMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.lp1, e.results.err
		}
	}

	if mmLocate.LocateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmLocate.LocateMock.defaultExpectation.Counter, 1)
		mm_want := mmLocate.LocateMock.defaultExpectation.params
		mm_want_ptrs := mmLocate.LocateMock.defaultExpectation.paramPtrs

		mm_got := WifiLocatorMockLocateParams{ctx, aps}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmLocate.t.Errorf("WifiLocatorMock.Locate got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLocate.LocateMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.aps != nil && !minimock.Equal(*mm_want_ptrs.aps, mm_got.aps) {
				mmLocate.t.Errorf("WifiLocatorMock.Locate got unexpected parameter aps, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmLocate.LocateMock.defaultExpectation.expectationOrigins.originAps, *mm_want_ptrs.aps, mm_got.aps, minimock.Diff(*mm_want_ptrs.aps, mm_got.aps))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmLocate.t.Errorf("WifiLocatorMock.Locate got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmLocate.LocateMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmLocate.LocateMock.defaultExpectation.results
		if mm_results == nil {
			mmLocate.t.Fatal("No results are set for the WifiLocatorMock.Locate")
		}
		return (*mm_results).lp1, (*mm_results).err
	}
	if mmLocate.funcLocate != nil {
		return mmLocate.funcLocate(ctx, aps)
	}
	mmLocate.t.Fatalf("Unexpected call to WifiLocatorMock.Locate. %v %v", ctx, aps)
	return
}

// LocateAfterCounter returns a count of finished WifiLocatorMock.Locate invocations
func (mmLocate *WifiLocatorMock) LocateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLocate.afterLocateCounter)
}

// LocateBeforeCounter returns a count of WifiLocatorMock.Locate invocations
func (mmLocate *WifiLocatorMock) LocateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmLocate.beforeLocateCounter)
}

// Calls returns a list of arguments used in each call to WifiLocatorMock.Locate.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmLocate *mWifiLocatorMockLocate) Calls() []*WifiLocatorMockLocateParams {
	mmLocate.mutex.RLock()

	argCopy := make([]*WifiLocatorMockLocateParams, len(mmLocate.callArgs))
	copy(argCopy, mmLocate.callArgs)

	mmLocate.mutex.RUnlock()

	return argCopy
}

// MinimockLocateDone returns true if the count of the Locate invocations corresponds
// the number of defined expectations
func (m *WifiLocatorMock) MinimockLocateDone() bool {
	if m.LocateMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.LocateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.LocateMock.invocationsDone()
}

// MinimockLocateInspect logs each unmet expectation
func (m *WifiLocatorMock) MinimockLocateInspect() {
	for _, e := range m.LocateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to WifiLocatorMock.Locate at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterLocateCounter := mm_atomic.LoadUint64(&m.afterLocateCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.LocateMock.defaultExpectation != nil && afterLocateCounter < 1 {
		if m.LocateMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to WifiLocatorMock.Locate at\n%s", m.LocateMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to WifiLocatorMock.Locate at\n%s with params: %#v", m.LocateMock.defaultExpectation.expectationOrigins.origin, *m.LocateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcLocate != nil && afterLocateCounter < 1 {
		m.t.Errorf("Expected call to WifiLocatorMock.Locate at\n%s", m.funcLocateOrigin)
	}

	if !m.LocateMock.invocationsDone() && afterLocateCounter > 0 {
		m.t.Errorf("Expected %d calls to WifiLocatorMock.Locate at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.LocateMock.expectedInvocations), m.LocateMock.expectedInvocationsOrigin, afterLocateCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *WifiLocatorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockLocateInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *WifiLocatorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *WifiLocatorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockLocateDone()
}
